baseURL = 'http://localhost:1313'
languageCode = 'en-gb'
title = "Scaling QC with Graph Rewriting"
theme = "hugo-book"
timeout = "60s"

[params]
BookSection = '*'
BookToC = false

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.extensions.typographer]
emDash = '&nbsp;&ndash;&nbsp;'

[markup.goldmark.extensions]
katex = true
[markup.goldmark.extensions.bibtex]
enable = true
bibtexPath = "thesis.bib"
[markup.goldmark.parser.attribute]
block = true
title = true
[markup.goldmark.renderHooks.image]
enableDefault = true

[markup.highlight]
style = "catppuccin-latte"
