baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'DPhil Thesis'
theme = "hugo-book"

[params]
BookSection = '*'

[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions.typographer]
    emDash = '&nbsp;&ndash;&nbsp;'

  [markup.goldmark.extensions]
    katex = true